trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  GOBIN:  '$(GOPATH)/bin'
  GOROOT: '/usr/local/go'
  GOPATH: '$(system.defaultWorkingDirectory)/gopath'
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)'

steps:
- script: |
    mkdir -p '$(GOBIN)'
    mkdir -p '$(GOPATH)/pkg'
    mkdir -p '$(modulePath)'
    shopt -s extglob
    shopt -s dotglob
    mv !(gopath) '$(modulePath)'
    echo '##vso[task.prependpath]$(GOBIN)'
    echo '##vso[task.prependpath]$(GOROOT)/bin'
  displayName: 'Configurar el espacio de trabajo de Go'

- script: |
    go version
    wget https://dl.google.com/go/go1.21.linux-amd64.tar.gz
    sudo tar -xvf go1.21.linux-amd64.tar.gz
    sudo mv go /usr/local
    export GOROOT=/usr/local/go
    export PATH=$GOROOT/bin:$PATH
    go version
    go mod download
    go build -v .
    go test ./...
  workingDirectory: '$(modulePath)'
  displayName: 'Obtener dependencias, compilar y ejecutar pruebas'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publicar artefactos de compilación'
